#!/usr/bin/env python3
"""Gera data/ruptura.json direto do Oracle Consinco (sem Excel).

Pipeline (8 queries, baseadas nas connections do Ruptura.xlsx):
  Q1 = COUNT geral por comprador×empresa (denominador GERAL)
  Q2 = COUNT rupturas geral (numerador GERAL)
  Q3 = COUNT 20x80 (denominador 20x80)
  Q4 = COUNT rupturas 20x80 (numerador 20x80)
  Q5 = Itens em ruptura com fornecedor/comprador/empresa/produto (Conn 11)
  Q6 = Média de venda dos itens zerados — geral (Conn 9)
  Q7 = Códigos 20x80 zerados — pra marcar flag is_20x80 (Conn 8)
  Q8 = Total de SKUs por fornecedor (denominador fornecedor — Conn 10 simplificado)

Cruza tudo em Python pra gerar o ruptura.json no mesmo formato do extract_ruptura.py
antigo (que lia o Excel).

Evolução diária NÃO é montada aqui — o servidor faz isso ao receber o upload,
salvando snapshot na tabela `ruptura_historico` e cruzando com histórico.
"""
import json
import os
import sys
import time
from collections import defaultdict
from datetime import datetime
from pathlib import Path

# Re-exec com LD_LIBRARY_PATH se ainda não estiver setado
ORACLE_LIB_DEFAULT = '/home/joaoreis/oracle/instantclient_23_7'
_lib = os.environ.get('ORACLE_LIB', ORACLE_LIB_DEFAULT)
_curr = os.environ.get('LD_LIBRARY_PATH', '')
if _lib not in _curr.split(':'):
    os.environ['LD_LIBRARY_PATH'] = f'{_lib}:{_curr}' if _curr else _lib
    os.execv(sys.executable, [sys.executable] + sys.argv)

import oracledb

ORACLE_USER = os.environ.get('ORACLE_USER', 'consinco')
ORACLE_PASSWORD = os.environ.get('ORACLE_PASSWORD', '')
ORACLE_DSN = os.environ.get('ORACLE_DSN', '10.61.1.1:1521/orcl')
OUT_PATH = Path('./data/ruptura.json')

# ===== Filtros comuns =====
NROEMPRESA_LIST = "5,7,29,10,101,102,103,104,106,108,11,112,125,13,131,14,16,109,117,18,20,21,215,219,222,23,26,27,28"
SEGMENTOS = "2,4,5,6,1,3"
SKU_EXCLUDE_BASE = "31629,31677,31610,31645,31637,31669,31661,31653"
# Lista grande de SKUs descontinuados — usada nas queries de RUPTURA (4,7) e ITENS (5,6,7)
SKU_EXCLUDE_LARGE = "28499,28497,31629,31677,31610,31645,31637,31669,31661,31653,6364,33480,32728,13145,7332,33481,32727,13380,33474,32724,13489,33475,32730,28709,13375,6367,13421,33476,32733,13268,6369,33477,32732,13506,33478,32729,13507,33479,32731,6372,13392,13657,33606,32725,14055,13693,33482,32726,28500,15988,28501,33498,32723,28498,13861,6378,7334,32722,13423,33483,28502,28490,28503,6380,33484,32721,13379,28504,6382,32720,13272,6383,33485,32715,14056,13694,33486,32719,13804,13390,28511,33487,28491,5368,15987,32716,14262,32717,32718,13383,15986,5892,13697,33488,32714,13874,28505,6387,33489,32713,13386,28506,15985,28496,13505,33490,32712,6390,15983,28489,33491,33492,13698,33493,33494,28507,15982,15981,15980,15979,28485,28494,15978,6394,33495,32710,13785,6396,33496,32709,13377,13699,33497,32708,13388,28510,28509,15977,15975"
SEQCATEGORIA_FILTER = "1,1946,1948,2195,3050,3004,2201,2197,2198,2196,2194,2231,2232,2828,2228,2726,2227,2230,2837,2226,2225,2900,2119,2123,2118,2539,2120"

# ============================================================
# Q1 — COUNT GERAL por (comprador, empresa) — denominador
# ============================================================
SQL_COUNT_GERAL = f"""
SELECT
    O.SEQCOMPRADOR as SEQCOMP,
    O.APELIDO as COMPRADOR,
    E.NROEMPRESA as NROEMP,
    E.NOMEREDUZIDO as EMPRESA,
    COUNT(DISTINCT C.SEQPRODUTO) as ITENS_SKU
FROM MAP_PRODUTO A,
     MAP_FAMILIA B,
     (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
             DECODE((ESTQLOJA + ESTQDEPOSITO), 0, NULL, Y.SEQPRODUTO) SEQPRODUTOCOMESTQ,
             DECODE(X.PRECO, 0, X.MENORPRECO, X.PRECO) PRECO,
             X.MENORPRECO, X.MAIORPRECO, Y.NROGONDOLA, Y.ESTQLOJA, Y.ESTQDEPOSITO,
             Y.STATUSCOMPRA, X.STATUSVENDA, Y.INDPOSICAOCATEG, SYSDATE DTAENTRADASAIDA
      FROM (SELECT SEQPRODUTO, NROEMPRESA,
                   MAX(QTDEMBALAGEM) QTDEMBALAGEMSEG,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0
                            THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM)
                       END) PRECO,
                   MIN(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0
                            THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM)
                       END) MENORPRECO,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0
                            THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM)
                       END) MAIORPRECO,
                   DECODE(MIN(STATUSVENDA), 'A', MIN(STATUSVENDA), 'I') STATUSVENDA
            FROM MRL_PRODEMPSEG
            WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
              AND NROSEGMENTO IN ({SEGMENTOS})
              AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
            GROUP BY SEQPRODUTO, NROEMPRESA) X,
           MRL_PRODUTOEMPRESA Y,
           MAX_EMPRESA E
      WHERE E.NROEMPRESA = Y.NROEMPRESA
        AND Y.NROEMPRESA = X.NROEMPRESA
        AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
     MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E,
     MAX_DIVISAO I2, MAX_COMPRADOR O, MAP_FAMDIVCATEG W,
     MAD_SEGMENTO SE, MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
WHERE A.SEQPRODUTO = C.SEQPRODUTO
  AND B.SEQFAMILIA = A.SEQFAMILIA
  AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
  AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
  AND K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
  AND E.NROEMPRESA = C.NROEMPRESA
  AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
  AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
  AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
  AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
  AND FDC.STATUS = 'A'
  AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
  AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
  AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
  AND C.STATUSCOMPRA IN ('A')
  AND D.SEQCOMPRADOR NOT IN (14,15)
  AND A.SEQFAMILIA NOT IN (SELECT SEQFAMILIA FROM MAP_FAMFORNEC WHERE SEQFORNECEDOR IN (1203,24935,25848,22230) AND PRINCIPAL = 'S')
  AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
  AND A.SEQPRODUTOBASE IS NULL
  AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
GROUP BY O.SEQCOMPRADOR, O.APELIDO, E.NROEMPRESA, E.NOMEREDUZIDO
ORDER BY O.APELIDO, E.NOMEREDUZIDO
"""

# ============================================================
# Q2 — COUNT RUPTURAS GERAL (zerados) — numerador
# ============================================================
SQL_RUPT_GERAL = f"""
SELECT
    O.SEQCOMPRADOR as SEQCOMP,
    O.APELIDO as COMPRADOR,
    E.NROEMPRESA as NROEMP,
    E.NOMEREDUZIDO as EMPRESA,
    COUNT(DISTINCT C.SEQPRODUTO) as ITENS_SKU
FROM MAP_PRODUTO A, MAP_FAMILIA B,
     (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
             DECODE((ESTQLOJA + ESTQDEPOSITO), 0, NULL, Y.SEQPRODUTO) SEQPRODUTOCOMESTQ,
             DECODE(X.PRECO, 0, X.MENORPRECO, X.PRECO) PRECO,
             X.MENORPRECO, X.MAIORPRECO, Y.ESTQLOJA, Y.ESTQDEPOSITO,
             Y.STATUSCOMPRA, X.STATUSVENDA, Y.INDPOSICAOCATEG, SYSDATE DTAENTRADASAIDA
      FROM (SELECT SEQPRODUTO, NROEMPRESA,
                   MAX(QTDEMBALAGEM) QTDEMBALAGEMSEG,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) PRECO,
                   MIN(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MENORPRECO,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MAIORPRECO,
                   DECODE(MIN(STATUSVENDA), 'A', MIN(STATUSVENDA), 'I') STATUSVENDA
            FROM MRL_PRODEMPSEG
            WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
              AND NROSEGMENTO IN ({SEGMENTOS})
              AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
            GROUP BY SEQPRODUTO, NROEMPRESA) X,
           MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E
      WHERE E.NROEMPRESA = Y.NROEMPRESA AND Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
     MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E,
     MAX_DIVISAO I2, MAX_COMPRADOR O, MAP_FAMDIVCATEG W,
     MAD_SEGMENTO SE, MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
WHERE A.SEQPRODUTO = C.SEQPRODUTO
  AND B.SEQFAMILIA = A.SEQFAMILIA
  AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
  AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
  AND K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
  AND E.NROEMPRESA = C.NROEMPRESA
  AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
  AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
  AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
  AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
  AND FDC.STATUS = 'A'
  AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
  AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
  AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
  AND C.STATUSCOMPRA IN ('A')
  AND D.SEQCOMPRADOR NOT IN (14,15)
  AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
  AND (ESTQLOJA + ESTQDEPOSITO) = 0
  AND A.SEQPRODUTOBASE IS NULL
  AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
GROUP BY O.SEQCOMPRADOR, O.APELIDO, E.NROEMPRESA, E.NOMEREDUZIDO
HAVING ROUND(ROUND(SUM((ESTQLOJA + ESTQDEPOSITO) / K.QTDEMBALAGEM), 6), 6) = 0
ORDER BY O.APELIDO, E.NOMEREDUZIDO
"""

# ============================================================
# Q3 — COUNT 20x80 (denominador 20x80)
# ============================================================
SQL_COUNT_20X80 = f"""
SELECT
    O.SEQCOMPRADOR as SEQCOMP,
    O.APELIDO as COMPRADOR,
    E.NROEMPRESA as NROEMP,
    E.NOMEREDUZIDO as EMPRESA,
    COUNT(DISTINCT C.SEQPRODUTO) as ITENS_SKU
FROM MAP_PRODUTO A, MAP_FAMILIA B,
     (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
             DECODE((ESTQLOJA + ESTQDEPOSITO), 0, NULL, Y.SEQPRODUTO) SEQPRODUTOCOMESTQ,
             DECODE(X.PRECO, 0, X.MENORPRECO, X.PRECO) PRECO,
             X.MENORPRECO, X.MAIORPRECO, Y.ESTQLOJA, Y.ESTQDEPOSITO,
             Y.STATUSCOMPRA, X.STATUSVENDA, Y.INDPOSICAOCATEG, SYSDATE DTAENTRADASAIDA
      FROM (SELECT SEQPRODUTO, NROEMPRESA,
                   MAX(QTDEMBALAGEM) QTDEMBALAGEMSEG,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) PRECO,
                   MIN(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MENORPRECO,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MAIORPRECO,
                   DECODE(MIN(STATUSVENDA), 'A', MIN(STATUSVENDA), 'I') STATUSVENDA
            FROM MRL_PRODEMPSEG
            WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
              AND NROSEGMENTO IN ({SEGMENTOS})
              AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
            GROUP BY SEQPRODUTO, NROEMPRESA) X,
           MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E
      WHERE E.NROEMPRESA = Y.NROEMPRESA AND Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
     MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E,
     MAX_DIVISAO I2, MAX_COMPRADOR O, MAP_FAMDIVCATEG W,
     MAD_SEGMENTO SE, MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
WHERE A.SEQPRODUTO = C.SEQPRODUTO
  AND B.SEQFAMILIA = A.SEQFAMILIA
  AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
  AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
  AND K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
  AND E.NROEMPRESA = C.NROEMPRESA
  AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
  AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
  AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
  AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
  AND FDC.STATUS = 'A'
  AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
  AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
  AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
  AND C.STATUSCOMPRA IN ('A')
  AND FSTATUSVENDAPRODUTO(C.SEQPRODUTO, C.NROEMPRESA, SE.NROSEGMENTO) = 'A'
  AND D.SEQCOMPRADOR NOT IN (14,15)
  AND A.SEQFAMILIA NOT IN (SELECT SEQFAMILIA FROM MAP_FAMFORNEC WHERE SEQFORNECEDOR IN (1203,24935,25848,22230) AND PRINCIPAL = 'S')
  AND A.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM MAP_PRODSIMILAR, MAP_SIMILARIDADE
                       WHERE MAP_SIMILARIDADE.SEQSIMILARIDADE = MAP_PRODSIMILAR.SEQSIMILARIDADE
                         AND MAP_SIMILARIDADE.TIPOSIMILARIDADE = 'P'
                         AND MAP_SIMILARIDADE.SEQSIMILARIDADE IN (297))
  AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
  AND A.SEQPRODUTOBASE IS NULL
  AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
GROUP BY O.SEQCOMPRADOR, O.APELIDO, E.NROEMPRESA, E.NOMEREDUZIDO
ORDER BY O.APELIDO, E.NOMEREDUZIDO
"""

# ============================================================
# Q4 — COUNT RUPTURAS 20x80 (numerador 20x80)
# ============================================================
SQL_RUPT_20X80 = f"""
SELECT
    O.SEQCOMPRADOR as SEQCOMP,
    O.APELIDO as COMPRADOR,
    E.NROEMPRESA as NROEMP,
    E.NOMEREDUZIDO as EMPRESA,
    COUNT(DISTINCT C.SEQPRODUTO) as ITENS_SKU
FROM MAP_PRODUTO A, MAP_FAMILIA B,
     (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
             DECODE((ESTQLOJA + ESTQDEPOSITO), 0, NULL, Y.SEQPRODUTO) SEQPRODUTOCOMESTQ,
             DECODE(X.PRECO, 0, X.MENORPRECO, X.PRECO) PRECO,
             X.MENORPRECO, X.MAIORPRECO, Y.ESTQLOJA, Y.ESTQDEPOSITO,
             Y.STATUSCOMPRA, X.STATUSVENDA, Y.INDPOSICAOCATEG, SYSDATE DTAENTRADASAIDA
      FROM (SELECT SEQPRODUTO, NROEMPRESA,
                   MAX(QTDEMBALAGEM) QTDEMBALAGEMSEG,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) PRECO,
                   MIN(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MENORPRECO,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MAIORPRECO,
                   DECODE(MIN(STATUSVENDA), 'A', MIN(STATUSVENDA), 'I') STATUSVENDA
            FROM MRL_PRODEMPSEG
            WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
              AND NROSEGMENTO IN ({SEGMENTOS})
              AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
            GROUP BY SEQPRODUTO, NROEMPRESA) X,
           MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E
      WHERE E.NROEMPRESA = Y.NROEMPRESA AND Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
     MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E,
     MAX_DIVISAO I2, MAX_COMPRADOR O, MAP_FAMDIVCATEG W,
     MAD_SEGMENTO SE, MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
WHERE A.SEQPRODUTO = C.SEQPRODUTO
  AND B.SEQFAMILIA = A.SEQFAMILIA
  AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
  AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
  AND K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
  AND E.NROEMPRESA = C.NROEMPRESA
  AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
  AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
  AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
  AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
  AND FDC.STATUS = 'A'
  AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
  AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
  AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
  AND C.STATUSCOMPRA IN ('A')
  AND FSTATUSVENDAPRODUTO(C.SEQPRODUTO, C.NROEMPRESA, SE.NROSEGMENTO) = 'A'
  AND D.SEQCOMPRADOR NOT IN (14,15)
  AND A.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM MAP_PRODSIMILAR, MAP_SIMILARIDADE
                       WHERE MAP_SIMILARIDADE.SEQSIMILARIDADE = MAP_PRODSIMILAR.SEQSIMILARIDADE
                         AND MAP_SIMILARIDADE.TIPOSIMILARIDADE = 'P'
                         AND MAP_SIMILARIDADE.SEQSIMILARIDADE IN (297))
  AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
  AND (ESTQLOJA + ESTQDEPOSITO) = 0
  AND A.SEQPRODUTOBASE IS NULL
  AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
GROUP BY O.SEQCOMPRADOR, O.APELIDO, E.NROEMPRESA, E.NOMEREDUZIDO
HAVING ROUND(ROUND(SUM((ESTQLOJA + ESTQDEPOSITO) / K.QTDEMBALAGEM), 6), 6) = 0
ORDER BY O.APELIDO, E.NOMEREDUZIDO
"""

# ============================================================
# Q5 — Itens em ruptura com fornecedor / comprador / loja / produto (Conn 11)
# ============================================================
SQL_ITENS_FORN = f"""
SELECT
    P.SEQPESSOA as SEQFORN,
    P.NOMERAZAO as FORNECEDOR,
    O.SEQCOMPRADOR as SEQCOMP,
    O.APELIDO as COMPRADOR,
    E.NROEMPRESA as NROEMP,
    E.NOMEREDUZIDO as EMPRESA,
    A.SEQPRODUTO as CODIGO_PRODUTO,
    A.DESCCOMPLETA as DESC_PRODUTO
FROM MAP_PRODUTO A, MAP_FAMILIA B,
     (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
             DECODE((ESTQLOJA + ESTQDEPOSITO), 0, NULL, Y.SEQPRODUTO) SEQPRODUTOCOMESTQ,
             DECODE(X.PRECO, 0, X.MENORPRECO, X.PRECO) PRECO,
             X.MENORPRECO, X.MAIORPRECO, Y.ESTQLOJA, Y.ESTQDEPOSITO,
             Y.STATUSCOMPRA, X.STATUSVENDA, Y.INDPOSICAOCATEG, SYSDATE DTAENTRADASAIDA
      FROM (SELECT SEQPRODUTO, NROEMPRESA,
                   MAX(QTDEMBALAGEM) QTDEMBALAGEMSEG,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) PRECO,
                   MIN(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MENORPRECO,
                   MAX(CASE WHEN STATUSVENDA = 'I' OR DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) = 0 THEN NULL
                            ELSE (DECODE(PRECOVALIDPROMOC, 0, PRECOVALIDNORMAL, PRECOVALIDPROMOC) / QTDEMBALAGEM) END) MAIORPRECO,
                   DECODE(MIN(STATUSVENDA), 'A', MIN(STATUSVENDA), 'I') STATUSVENDA
            FROM MRL_PRODEMPSEG
            WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
              AND NROSEGMENTO IN ({SEGMENTOS})
              AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
            GROUP BY SEQPRODUTO, NROEMPRESA) X,
           MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E
      WHERE E.NROEMPRESA = Y.NROEMPRESA AND Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
     MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E,
     MAX_DIVISAO I2, MAP_FAMFORNEC F, GE_PESSOA P, MAX_COMPRADOR O,
     MAP_FAMDIVCATEG W, MAD_SEGMENTO SE, MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
WHERE A.SEQPRODUTO = C.SEQPRODUTO
  AND B.SEQFAMILIA = A.SEQFAMILIA
  AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
  AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
  AND K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
  AND E.NROEMPRESA = C.NROEMPRESA
  AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
  AND F.SEQFAMILIA = A.SEQFAMILIA AND F.PRINCIPAL = 'S'
  AND P.SEQPESSOA = F.SEQFORNECEDOR
  AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
  AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
  AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
  AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
  AND FDC.STATUS = 'A'
  AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
  AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
  AND C.STATUSCOMPRA IN ('A')
  AND D.SEQCOMPRADOR NOT IN (14,15)
  AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
  AND (ESTQLOJA + ESTQDEPOSITO) = 0
  AND A.SEQPRODUTOBASE IS NULL
  AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
GROUP BY P.SEQPESSOA, P.NOMERAZAO, O.SEQCOMPRADOR, O.APELIDO,
         E.NROEMPRESA, E.NOMEREDUZIDO, A.SEQPRODUTO, A.DESCCOMPLETA
HAVING ROUND(ROUND(SUM((ESTQLOJA + ESTQDEPOSITO) / K.QTDEMBALAGEM), 6), 6) = 0
ORDER BY P.NOMERAZAO, O.APELIDO, E.NOMEREDUZIDO, A.DESCCOMPLETA
"""

# ============================================================
# Q6 — Média de venda dos itens zerados — geral (Conn 9)
# ============================================================
SQL_MEDIA_GERAL = f"""
SELECT
    E.NROEMPRESA as NROEMP,
    A.SEQPRODUTO as CODIGO_PRODUTO,
    SUM(C.MEDVDIAGERAL / K.QTDEMBALAGEM) as MEDIA_VENDA
FROM MAP_PRODUTO A
INNER JOIN MAP_FAMILIA B ON B.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN (
    SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.MEDVDIAGERAL,
           Y.ESTQLOJA, Y.ESTQDEPOSITO, Y.STATUSCOMPRA
    FROM (SELECT SEQPRODUTO, NROEMPRESA
          FROM MRL_PRODEMPSEG
          WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
            AND NROSEGMENTO IN ({SEGMENTOS})
            AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
          GROUP BY SEQPRODUTO, NROEMPRESA) X
    INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO
) C ON A.SEQPRODUTO = C.SEQPRODUTO
INNER JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN MAP_FAMEMBALAGEM K ON K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = C.NROEMPRESA AND D.NRODIVISAO = E.NRODIVISAO
INNER JOIN MAP_FAMDIVCATEG W ON W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
INNER JOIN MAD_FAMSEGMENTO H ON H.SEQFAMILIA = A.SEQFAMILIA AND H.NROSEGMENTO = E.NROSEGMENTOPRINC
INNER JOIN MAD_SEGMENTO SE ON SE.NROSEGMENTO = H.NROSEGMENTO
WHERE C.NROEMPRESA IN ({NROEMPRESA_LIST})
AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
AND C.STATUSCOMPRA IN ('A')
AND fstatusvendaproduto(C.SEQPRODUTO, C.NROEMPRESA, SE.NROSEGMENTO) = 'A'
AND D.SEQCOMPRADOR NOT IN (14, 15)
AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
AND (C.ESTQLOJA + C.ESTQDEPOSITO) = 0
AND A.SEQPRODUTOBASE IS NULL
GROUP BY E.NROEMPRESA, A.SEQPRODUTO
HAVING ROUND(SUM((C.ESTQLOJA + C.ESTQDEPOSITO) / K.QTDEMBALAGEM), 6) = 0
"""

# ============================================================
# Q7 — Códigos 20x80 zerados (pra marcar flag is_20x80)
# Usa filtro IN (SEQSIMILARIDADE 297) — esse é o "20x80"
# ============================================================
SQL_ITENS_20X80 = f"""
SELECT
    E.NROEMPRESA as NROEMP,
    A.SEQPRODUTO as CODIGO_PRODUTO
FROM MAP_PRODUTO A
INNER JOIN MAP_FAMILIA B ON B.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN (
    SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.MEDVDIAGERAL,
           Y.ESTQLOJA, Y.ESTQDEPOSITO, Y.STATUSCOMPRA
    FROM (SELECT SEQPRODUTO, NROEMPRESA
          FROM MRL_PRODEMPSEG
          WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
            AND NROSEGMENTO IN ({SEGMENTOS})
            AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
          GROUP BY SEQPRODUTO, NROEMPRESA) X
    INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO
) C ON A.SEQPRODUTO = C.SEQPRODUTO
INNER JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN MAP_FAMEMBALAGEM K ON K.SEQFAMILIA = D.SEQFAMILIA AND K.QTDEMBALAGEM = 1
INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = C.NROEMPRESA AND D.NRODIVISAO = E.NRODIVISAO
INNER JOIN MAP_FAMDIVCATEG W ON W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
INNER JOIN MAD_FAMSEGMENTO H ON H.SEQFAMILIA = A.SEQFAMILIA AND H.NROSEGMENTO = E.NROSEGMENTOPRINC
INNER JOIN MAD_SEGMENTO SE ON SE.NROSEGMENTO = H.NROSEGMENTO
WHERE C.NROEMPRESA IN ({NROEMPRESA_LIST})
AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
AND C.STATUSCOMPRA IN ('A')
AND fstatusvendaproduto(C.SEQPRODUTO, C.NROEMPRESA, SE.NROSEGMENTO) = 'A'
AND D.SEQCOMPRADOR NOT IN (14, 15)
AND A.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM MAP_PRODSIMILAR, MAP_SIMILARIDADE
                     WHERE MAP_SIMILARIDADE.SEQSIMILARIDADE = MAP_PRODSIMILAR.SEQSIMILARIDADE
                       AND MAP_SIMILARIDADE.TIPOSIMILARIDADE = 'P'
                       AND MAP_SIMILARIDADE.SEQSIMILARIDADE IN (297))
AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_LARGE})
AND (C.ESTQLOJA + C.ESTQDEPOSITO) = 0
AND A.SEQPRODUTOBASE IS NULL
GROUP BY E.NROEMPRESA, A.SEQPRODUTO
HAVING ROUND(SUM((C.ESTQLOJA + C.ESTQDEPOSITO) / K.QTDEMBALAGEM), 6) = 0
"""

# ============================================================
# Q8 — Total de SKUs (combinação loja×produto) por fornecedor (denominador)
# Mesma estrutura da Q5, mas SEM o filtro de estoque=0.
# ============================================================
SQL_FORN_TOTAL = f"""
SELECT
    SEQPESSOA as SEQFORN,
    NOMERAZAO as FORNECEDOR,
    COUNT(*) as ITENS_SKU
FROM (
    SELECT DISTINCT
        P.SEQPESSOA, P.NOMERAZAO,
        E.NROEMPRESA, A.SEQPRODUTO
    FROM MAP_PRODUTO A, MAP_FAMILIA B,
         (SELECT Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER,
                 Y.STATUSCOMPRA, Y.ESTQLOJA, Y.ESTQDEPOSITO
          FROM (SELECT SEQPRODUTO, NROEMPRESA FROM MRL_PRODEMPSEG
                WHERE NROEMPRESA IN ({NROEMPRESA_LIST})
                  AND NROSEGMENTO IN ({SEGMENTOS})
                  AND SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
                GROUP BY SEQPRODUTO, NROEMPRESA) X,
               MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E
          WHERE E.NROEMPRESA = Y.NROEMPRESA AND Y.NROEMPRESA = X.NROEMPRESA AND Y.SEQPRODUTO = X.SEQPRODUTO) C,
         MAP_FAMDIVISAO D, MAX_EMPRESA E, MAX_DIVISAO I2,
         MAP_FAMFORNEC F, GE_PESSOA P, MAX_COMPRADOR O,
         MAP_FAMDIVCATEG W, MAD_SEGMENTO SE,
         MAP_FAMDIVCATEG FDC, MAP_CATEGORIA CAT
    WHERE A.SEQPRODUTO = C.SEQPRODUTO
      AND B.SEQFAMILIA = A.SEQFAMILIA
      AND C.NROEMPRESA IN ({NROEMPRESA_LIST})
      AND D.SEQFAMILIA = A.SEQFAMILIA AND D.NRODIVISAO = E.NRODIVISAO
      AND E.NROEMPRESA = C.NROEMPRESA
      AND I2.NRODIVISAO = E.NRODIVISAO AND I2.NRODIVISAO = D.NRODIVISAO
      AND F.SEQFAMILIA = A.SEQFAMILIA AND F.PRINCIPAL = 'S'
      AND P.SEQPESSOA = F.SEQFORNECEDOR
      AND O.SEQCOMPRADOR = D.SEQCOMPRADOR
      AND A.SEQFAMILIA = FDC.SEQFAMILIA AND CAT.NRODIVISAO = E.NRODIVISAO
      AND FDC.SEQCATEGORIA = CAT.SEQCATEGORIA AND FDC.NRODIVISAO = CAT.NRODIVISAO
      AND CAT.NIVELHIERARQUIA = 1 AND CAT.STATUSCATEGOR IN ('A','F') AND CAT.TIPCATEGORIA = 'M'
      AND FDC.STATUS = 'A'
      AND W.SEQFAMILIA = D.SEQFAMILIA AND W.NRODIVISAO = D.NRODIVISAO AND W.STATUS = 'A'
      AND W.SEQCATEGORIA IN ({SEQCATEGORIA_FILTER})
      AND C.STATUSCOMPRA IN ('A')
      AND D.SEQCOMPRADOR NOT IN (14,15)
      AND A.SEQFAMILIA NOT IN (SELECT SEQFAMILIA FROM MAP_FAMFORNEC WHERE SEQFORNECEDOR IN (1203,24935,25848,22230) AND PRINCIPAL = 'S')
      AND A.SEQPRODUTO NOT IN ({SKU_EXCLUDE_BASE})
      AND A.SEQPRODUTOBASE IS NULL
      AND SE.NROSEGMENTO = E.NROSEGMENTOPRINC
)
GROUP BY SEQPESSOA, NOMERAZAO
"""


def run_query(cur, label, sql):
    t = time.time()
    print(f'  → {label}…', end='', flush=True)
    cur.execute(sql)
    rows = cur.fetchall()
    print(f' {len(rows)} linhas em {time.time()-t:.1f}s')
    return rows


def main():
    if not ORACLE_PASSWORD:
        print('ERRO: ORACLE_PASSWORD não definida no .env', file=sys.stderr); sys.exit(1)

    print(f'conectando em {ORACLE_DSN} como {ORACLE_USER}…')
    oracledb.init_oracle_client(lib_dir=os.environ['LD_LIBRARY_PATH'].split(':')[0])
    conn = oracledb.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=ORACLE_DSN)
    cur = conn.cursor()

    rows_count_geral  = run_query(cur, 'Q1 count GERAL',     SQL_COUNT_GERAL)
    rows_rupt_geral   = run_query(cur, 'Q2 rupt GERAL',      SQL_RUPT_GERAL)
    rows_count_20     = run_query(cur, 'Q3 count 20x80',     SQL_COUNT_20X80)
    rows_rupt_20      = run_query(cur, 'Q4 rupt 20x80',      SQL_RUPT_20X80)
    rows_itens_forn   = run_query(cur, 'Q5 itens fornecedor',SQL_ITENS_FORN)
    rows_media        = run_query(cur, 'Q6 media venda',     SQL_MEDIA_GERAL)
    rows_20x80_keys   = run_query(cur, 'Q7 chaves 20x80',    SQL_ITENS_20X80)
    rows_forn_total   = run_query(cur, 'Q8 forn total',      SQL_FORN_TOTAL)

    cur.close(); conn.close()

    # ---- agregação de compradores e lojas (geral e 20x80) ----
    def agrega_por(rows, idx_chave, idx_nome, idx_count):
        """Soma idx_count por idx_chave; guarda também o nome (idx_nome)."""
        somas = defaultdict(float)
        nomes = {}
        for r in rows:
            chave = r[idx_chave]
            somas[chave] += float(r[idx_count] or 0)
            nomes[chave] = r[idx_nome]
        return somas, nomes

    # Compradores: chave=SEQCOMP, nome=COMPRADOR, count=ITENS_SKU
    cont_comp_geral,  nome_comp = agrega_por(rows_count_geral,  0, 1, 4)
    rupt_comp_geral,  _         = agrega_por(rows_rupt_geral,   0, 1, 4)
    cont_comp_20,     nome_comp_20 = agrega_por(rows_count_20,  0, 1, 4)
    rupt_comp_20,     _         = agrega_por(rows_rupt_20,      0, 1, 4)
    nome_comp.update(nome_comp_20)

    # Lojas: chave=NROEMP, nome=EMPRESA
    cont_loja_geral,  nome_loja = agrega_por(rows_count_geral,  2, 3, 4)
    rupt_loja_geral,  _         = agrega_por(rows_rupt_geral,   2, 3, 4)
    cont_loja_20,     nome_loja_20 = agrega_por(rows_count_20,  2, 3, 4)
    rupt_loja_20,     _         = agrega_por(rows_rupt_20,      2, 3, 4)
    nome_loja.update(nome_loja_20)

    def ranking(cont_dict, rupt_dict, nomes):
        out = []
        for chave, total in cont_dict.items():
            zer = rupt_dict.get(chave, 0)
            out.append({
                'nome':    nomes.get(chave, str(chave)),
                'skus':    total,
                'zerados': zer,
                'pct':     (zer / total) if total else 0,
            })
        out.sort(key=lambda x: -x['pct'])
        for i, r in enumerate(out, 1):
            r['rank'] = i
        return out

    ranking_compradores = {
        'geral': ranking(cont_comp_geral, rupt_comp_geral, nome_comp),
        '20x80': ranking(cont_comp_20,    rupt_comp_20,    nome_comp),
    }
    ranking_lojas = {
        'geral': ranking(cont_loja_geral, rupt_loja_geral, nome_loja),
        '20x80': ranking(cont_loja_20,    rupt_loja_20,    nome_loja),
    }

    # ---- itens detalhados ----
    # rows_itens_forn cols: 0=SEQFORN 1=FORNECEDOR 2=SEQCOMP 3=COMPRADOR 4=NROEMP 5=EMPRESA 6=CODIGO 7=DESC
    media_idx = {(int(r[0]), int(r[1])): float(r[2] or 0) for r in rows_media}  # (NROEMP, COD) -> media
    keys_20x80 = {(int(r[0]), int(r[1])) for r in rows_20x80_keys}              # set de (NROEMP, COD)

    itens = []
    for r in rows_itens_forn:
        nroemp = int(r[4])
        cod = int(r[6])
        loja = f"{nroemp:02d}-{r[5]}" if isinstance(r[5], str) else str(r[5])
        comprador = f"{int(r[2])} - {r[3]}" if r[2] is not None else r[3]
        itens.append({
            'loja':        loja,
            'comprador':   comprador,
            'fornecedor':  r[1],
            'produto':     r[7],
            'codigo':      cod,
            'media_venda': media_idx.get((nroemp, cod)),
            'is_20x80':    (nroemp, cod) in keys_20x80,
        })

    # ---- ranking fornecedores ----
    # rows_forn_total: SEQFORN, FORNECEDOR, ITENS_SKU
    total_forn = {int(r[0]): float(r[2] or 0) for r in rows_forn_total}
    nome_forn  = {int(r[0]): r[1] for r in rows_forn_total}
    rupt_forn  = defaultdict(float)
    for r in rows_itens_forn:
        rupt_forn[int(r[0])] += 1
        if int(r[0]) not in nome_forn:
            nome_forn[int(r[0])] = r[1]

    ranking_fornecedores = []
    for sid, zer in rupt_forn.items():
        total = total_forn.get(sid, zer)  # se fornecedor não veio na Q8, assume total = zerados
        ranking_fornecedores.append({
            'nome':    nome_forn.get(sid, str(sid)),
            'skus':    total,
            'zerados': zer,
            'pct':     (zer / total) if total else 0,
        })
    ranking_fornecedores.sort(key=lambda x: -x['pct'])

    # ---- KPIs globais ----
    def total_de(lista_rank):
        if not lista_rank: return None
        skus = sum(r.get('skus') or 0 for r in lista_rank)
        zer  = sum(r.get('zerados') or 0 for r in lista_rank)
        return {'skus': skus, 'zerados': zer, 'pct': (zer / skus) if skus else 0}

    kpis = {
        'total_geral':  total_de(ranking_compradores['geral']),
        'total_20x80':  total_de(ranking_compradores['20x80']),
        'meta_geral':   0.12,
        'fornecedores_em_ruptura': len([f for f in ranking_fornecedores if (f.get('pct') or 0) >= 1.0]),
    }

    out = {
        'gerado_em': datetime.now().isoformat(timespec='seconds'),
        'kpis': kpis,
        # evolucao_diaria é montada pelo servidor (a partir de ruptura_historico)
        'evolucao_diaria': {'datas': [], 'geral': [], '20x80': []},
        'ranking_compradores': ranking_compradores,
        'ranking_lojas': ranking_lojas,
        'ranking_fornecedores': ranking_fornecedores,
        'itens': itens,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, ensure_ascii=False, default=str), encoding='utf-8')

    print()
    print(f'✓ salvo em {OUT_PATH} ({OUT_PATH.stat().st_size // 1024} KB)')
    print(f'Compradores (geral): {len(ranking_compradores["geral"])} · (20x80): {len(ranking_compradores["20x80"])}')
    print(f'Lojas (geral): {len(ranking_lojas["geral"])} · (20x80): {len(ranking_lojas["20x80"])}')
    print(f'Fornecedores em ruptura: {len(ranking_fornecedores)}')
    print(f'Itens zerados: {len(itens)} (20x80: {sum(1 for i in itens if i["is_20x80"])})')
    if kpis['total_geral']:
        k = kpis['total_geral']
        print(f'KPI geral: {k["skus"]:.0f} SKUs · {k["zerados"]:.0f} zerados · {k["pct"]*100:.2f}%')
    if kpis['total_20x80']:
        k = kpis['total_20x80']
        print(f'KPI 20x80: {k["skus"]:.0f} SKUs · {k["zerados"]:.0f} zerados · {k["pct"]*100:.2f}%')


if __name__ == '__main__':
    main()
